### ISSUE TITLE
Setting LogRetention and Tracing on Lambda leads to errors

### ISSUE THREAD

**Issue by drissamri** [cdklabs/cdk-nag#1076]
### General Issue

 AwsSolutions-IAM5 and  AwsSolutions-IAM4 are too strict on Lambda

### The Question

When deploying a default CDK Lambda with logRetention and tracing multiple AwsSolutions-IAM5 & AwsSolutions-IAM4 errors come up. 
```
        return new NodejsFunction(this, id, {
            functionName: name,
            entry: path.join(__dirname, '../../app/' + handler),
            runtime: lambda.Runtime.NODEJS_16_X,
            handler: 'handler',
            logRetention: RetentionDays.ONE_MONTH,
            tracing: lambda.Tracing.ACTIVE,
        });
  ```
  
It feels like all best practices are following by just deploying this? 

- Lambda uses AWSLambdaBasicExecutionRole and is flagged, is it recommended to override this role for Lambda?
- setting logRetention: RetentionDays.ONE_MONTH deploys an CDK managed Lambda which use the AWSLambdaBasicExecutionRole which is also flagged
-  setting lambda.Tracing.ACTIVE sets Allow: xray:PutTelemetryRecords & Allow: xray:PutTraceSegments on `*` Resource but these are not possible to scope down further 

It feels wrong to have to supress these in all Lambda projects by default for users? 

### cdk-nag version

2.20.2

### Language

Typescript

**Comment by dontirun** [comment]
It's ultimately up to you as a user what you want to do in this case.


1. There are tradeoffs to using managed policies. They are simple to use, but they can be updated at any time by AWS and can sometimes be overly permissive. With that in mind some users are okay with using certain managed policies, some are not.

2. As you noted `*` resources are required in some cases. That rule isn't "intelligent", but it can help you inspect your code for any potential issues and take action if so desired
