### ISSUE TITLE
doc: AwsSolutions-APIG4: The API does not implement authorization.

### ISSUE THREAD

**Issue by greenpau** [cdklabs/cdk-nag#1100]
### Describe your issue?

I receive the following error:

```
[Error at /ApiService/Instance/Default/OPTIONS/Resource] AwsSolutions-APIG4: The API does not implement authorization.
```

Upon further inspection, I discover that the following protects all methods, but the `OPTIONS` method.

```
const gateway = new apigateway.LambdaRestApi(this, "Instance", {
    ...
            defaultMethodOptions: {
                authorizationType: apigateway.AuthorizationType.COGNITO,
                authorizer,
            },
    ...
        });
```

Found the following discussion relevant to this topic: https://stackoverflow.com/questions/67336080/cdk-api-gateway-default-authorizer-exclude-options-method

What is the way to enable authorization for `OPTIONS`?

**Comment by dontirun** [comment]
Do you have a reproduceable example? If you are  a properly creating an `OPTIONS` method and applying authorization to it this may be a better issue to raise with the CDK than here.

If it is a CDK issue that needs to be resolved you may need to [follow this example from the README](https://github.com/cdklabs/cdk-nag/blob/main/README.md#rules-and-property-overrides) to resolve this isntance
