### ISSUE TITLE
doc: AwsSolutions-CFR4: The CloudFront distribution allows for SSLv3 or TLSv1 for HTTPS viewer connections.

### ISSUE THREAD

**Issue by greenpau** [cdklabs/cdk-nag#1101]
### Describe your issue?

> AwsSolutions-CFR4: The CloudFront distribution allows for SSLv3 or TLSv1 for HTTPS viewer connections.

Per recommendation under https://github.com/cdklabs/cdk-nag/blob/main/RULES.md#errors

> AwsSolutions-CFR4 
> The CloudFront distribution allows for SSLv3 or TLSv1 for HTTPS viewer connections.
> Vulnerabilities have been and continue to be discovered in the deprecated SSL and TLS protocols. Help protect viewer connections by specifying a viewer certificate that enforces a minimum of TLSv1.1 or TLSv1.2 in the security policy. Distributions that use the default CloudFront viewer certificate or use 'vip' for the SslSupportMethod are non-compliant with this rule, as the minimum security policy is set to TLSv1 regardless of the specified MinimumProtocolVersion

</body>
</html> 

I tried the following. However, that did not resolve the issue

```
            minimumProtocolVersion: cdk.aws_cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
            sslSupportMethod: cdk.aws_cloudfront.SSLMethod.SNI,
```

Related: https://github.com/aws/aws-cdk/issues/6547

**Comment by dontirun** [comment]
>    Distributions that use the default CloudFront viewer certificate or use 'vip' for the SslSupportMethod are non-compliant with this rule, as the minimum security policy is set to TLSv1 regardless of the specified MinimumProtocolVersion


Are you using the Default viewer certificate?

**Comment by greenpau** [comment]
> Are you using the Default viewer certificate?

@dontirun , yes, i.e. I am not setting up a separate cert. I use whatever cert cloudfront provides.

**Comment by dontirun** [comment]
Do you have a code example to reproduce the issue?

**Comment by neilferreira** [comment]
@greenpau how did you fix this issue?

**Comment by amberzaragoza** [comment]
Curious how this was fixed as well.
