### ISSUE TITLE
cdk-nag rule: VPCDefaultSecurityGroupClosed by definition cannot evaluate COMPLIANT

### ISSUE THREAD

**Issue by dboyd13** [cdklabs/cdk-nag#1133]
### General Issue

cdk-nag rule: VPCDefaultSecurityGroupClosed by definition cannot evaluate COMPLIANT

### The Question

The cdk-nag rule [`VPCDefaultSecurityGroupClosed`](https://github.com/cdklabs/cdk-nag/blob/main/src/rules/vpc/VPCDefaultSecurityGroupClosed.ts) has the following description within the [NIST-800-53-r4 pack](https://github.com/cdklabs/cdk-nag/blob/5ba357c98a4cfe7fab034537172f49c72f5dcc2c/src/packs/nist-800-53-r4.ts#L865):

> When creating a VPC through CloudFormation, the default security group will always be open. Therefore it is important to always close the default security group after stack creation whenever a VPC is created. Restricting all the traffic on the default security group helps in restricting remote access to your AWS resources.

It is my understanding that it is not possible to create CloudFormation (and by extension CDK code) that allows this rule to evaluate as `COMPLIANT`. This appears to be supported there not being a `NON_COMPLIANT` test-case in the [VPC rule related tests](https://github.com/cdklabs/cdk-nag/blob/0da7426acfdab38a35142e3ce9322cc04d39dbd1/test/rules/VPC.test.ts#L42).

**Question:** Is there value in this check existing within cdk-nag if it cannot be made compliant via CloudFormation/CDK?, Should this be depreciated and one should instead use a run-time detection such as the [vpc-default-security-group-closed](https://docs.aws.amazon.com/config/latest/developerguide/vpc-default-security-group-closed.html) AWS Config Managed Rule?

### cdk-nag version

2.21.4

### Language

Typescript

**Comment by dontirun** [comment]
> This appears to be supported there not being a NON_COMPLIANT test-case in the VPC rule related tests.

I believe you meant that there is no `COMPLIANT` test, but yes there is currently no out of the box way of adhering to the rule

> Should this be depreciated and one should instead use a run-time detection such as the vpc-default-security-group-closed AWS Config Managed Rule?

I don't this is an "either or" situation. Why not have both? We know that the resource is non-compliant to that rule so we alert on it (even there is no native method to fix it). The rule allows developers to immediately know that they may need to take action on the resource. It can be remmediated through some other method (such as a custom resource) and could additionally be suppressed with a description on what that action was.

**Comment by dboyd13** [comment]
Given that all current packs (PCI DSS 3.2.1, NIST 800-53-r4, NIST 800-53-r5, HIPPA Security) using this rule have it scoped to the `WARN` level... I think your views are fair enough. Closing.
