### ISSUE TITLE
doc: Intended usage on a construct library?

### ISSUE THREAD

**Issue by mvs5465** [cdklabs/cdk-nag#1135]
### Describe your issue?

We are developing a library of constructs for CDK. This library does not instantiate any apps or stacks, it serves only to export constructs. What is the expected way to test a construct library like this?

I tried adding Aspects to a unit test like this: https://github.com/aws-samples/aws-cdk-examples/blob/9c88ce300037bd0fbc25b900cae8f28a2863046f/typescript/s3-kms-cross-account-replication/test/s3-replication.test.ts#L54

However this did not work. There are no cdk-nag warnings or errors printed during the unit test. 

What is the intended way to run cdk-nag on a library of constructs that does not initialize any stacks or apps?

**Comment by mvs5465** [comment]
This method seems to work: https://github.com/cdklabs/cdk-nag/issues/728

**Comment by dontirun** [comment]
@mvs5465  I gather that this is for a construct library that is meant for a wide audience. 

In that case I would advise not putting suppressions in the actual construct code and only in the unit tests ([example](https://github.com/dontirun/state-machine-semaphore/blob/main/test/CdkNag.test.ts)). Putting suppressions in the actual code for constructs intended for a general audience is bad practice as that makes decisions for consumers
