### ISSUE TITLE
bug: short issue description

### ISSUE THREAD

**Issue by crnkyunicorn** [cdklabs/cdk-nag#1158]
### What is the problem?

Getting an error when using a PYTHON_3_9 lambda function.  

AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version.

The version I am using is the latest version that Lambda support of Python 3.9

### Reproduction Steps

Create lambda function using 

`runtime=aws_lambda.Runtime.PYTHON_3_9,`

### What did you expect to happen?

No cdk-nag errors

### What actually happened?

Error AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version. 

### cdk-nag version

2.21.58

### Language

Python

**Comment by dontirun** [comment]
Hey! There isn't enough information here to diagnose the problem.

Can you provide a small example the reproduces the problem with the full error message (including the path)
