### ISSUE TITLE
feat: S3 encrypts all new objects by default

### ISSUE THREAD

**Issue by clueleaf** [cdklabs/cdk-nag#1190]
### Description

Starting January 5th 2023, S3 encrypts all new objects by default.

https://aws.amazon.com/blogs/aws/amazon-s3-encrypts-new-objects-by-default/

I think it is safe to remove `S3BucketServerSideEncryptionEnabled` rule.

### Use Case

It is unnecessary to check server-side encryption setting anymore.

### Proposed Solution

Remove `S3BucketServerSideEncryptionEnabled` rule.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by dontirun** [comment]
Thanks for the contribution 🎉
