### ISSUE TITLE
Ensure S3 bucket does not have public write access

### ISSUE THREAD

**Issue by jen-rich** [cdklabs/cdk-nag#127]
*Control ID:*
AC-3/AC-4/AC-6/AC-21(b)/SC-7/SC-7(3)

*AWS Config Rule:* 
s3-bucket-public-write-prohibited

*Story:*
As an AWS consultant
I would like to check if my S3 bucket configuration is compliant (does not have public write access)
So that I can check if my application conforms with Control IDs AC-3, AC-4, AC-6, AC-21(b), SC-7, and SC-7(3) within NIST 800-53.

*Acceptance Criteria:*

    * Given a CDK stack with *a* *non-compliant S3* bucket
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant S3 bucket for Control IDs AC-3, AC-4, AC-6, AC-21(b), SC-7, and SC-7(3) within NIST 800-53 .
    * Given a CDK stack with *a* *compliant S3* bucket and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53.
    * Given a CDK stack *without an S3* bucket and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53

**Comment by dontirun** [comment]
This rule should be implementable, S3 Buckets have [this setting](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-publicaccessblockconfiguration) which can be checked
