### ISSUE TITLE
bug: Lambda runtime version numbers are sorted improperly when minor versions exceed 9

### ISSUE THREAD

**Issue by simonkrol** [cdklabs/cdk-nag#1271]
### What is the problem?

Once a minor version gets to 10, Eg: python3.10, the LambdaLatestVersion.ts nag rule considers it to be the same as python3.1, causing nags where there shouldn't be any.

### Reproduction Steps

Run cdk_nag on a stack which declares 

```
my_lambda = lambda_.Function(
    handler = "some_handler",
    runtime=lambda_.Runtime.PYTHON_3_10,
    code=lambda_Code.from_asset("my_code"),
    description="Some description")
```

### What did you expect to happen?

I'd expect not to get an CDK Nag to upgrade my python runtime.

### What actually happened?

"data": "AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version. Use the latest available runtime for the targeted language to avoid technical debt. Runtimes specific to a language or framework version are deprecated when the version reaches end of life. This rule only applies to non-container Lambda functions.\n",

### cdk-nag version

v2.26.5

### Language

Python

### Other information

If no one is presently working on this, I do have a fix available and can send in a PR.

**Comment by dontirun** [comment]
Thanks for reporting. PRs are welcome!Here are links to the [Contributing Guidlines](https://github.com/cdklabs/cdk-nag/blob/main/CONTRIBUTING.md) and [Rule Creation/Editing docs](https://github.com/cdklabs/cdk-nag/blob/main/docs/RuleCreation.md) to help get started
