### ISSUE TITLE
CrossRegionSupportStacks Compatibility

### ISSUE THREAD

**Issue by msaavedra-earnd** [cdklabs/cdk-nag#1298]
### General Issue

Props Compatibility

### The Question

Currently my Pipeline is creating a [CrossRegionSupportStacks](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CodePipeline.html#reusecrossregionsupportstacks) by default. When trying to make a suppression rule by path, using `addResourceSuppressionsByPath`, I am unable to reference that default Support Stack that Codepipeline creates. If I use `this` and `${this.stackName}`, I only reference the actual stack which is **SharedInfraPipelineStack**. 

This is the rule I'm trying to add:
```
    NagSuppressions.addResourceSuppressionsByPath(this, `/${this.stackName}/Default/CrossRegionCodePipelineReplicationBucket/Resource`, [
      {
        id: "AwsSolutions-S1",
        reason:
          "Artifact Bucket created by default by CDK to store the Artifacts.",
      },
    ]);
```

This is the error I always get:
```
[Error at /cross-region-stack-12345678901:us-east-1/Default/CrossRegionCodePipelineReplicationBucket/Resource] AwsSolutions-S1: The S3 Bucket has server access logs disabled. The bucket should have server access logging enabled to provide detailed records for the requests that are made to the bucket.
```
And if I try to build the Stack name to pass it, `addResourceSuppressionsByPath` does not allow me because it expects a Stack parameter and not a string.

For example, something like:
```
    const supportStackId = `cross-region-stack-12345678901:us-east-1`;

    NagSuppressions.addResourceSuppressionsByPath(supportStackId, `/${supportStackId}/Default/CrossRegionCodePipelineReplicationBucket/Resource`, [
      {
        id: "AwsSolutions-S1",
        reason:
          "Artifact Bucket created by default by CDK to store the Artifacts.",
      },
    ]);
```

How could I reference that **CrossRegionSupportStacks**? In this case is **cross-region-stack-12345678901:us-east-1** in my suppress rule?

### cdk-nag version

2.27.3

### Language

Typescript

**Comment by dontirun** [comment]
Hmm, you may be able to lookup up the stack from the parent `app` after instantiating the pipeline and then apply the suppression that way. Something like this may work 

```ts
const app = new App();
// pipeline setup code here
const supportStack = app.node.findChild('cross-region-stack-12345678901:us-east-1') as Stack;
NagSuppressions.addResourceSuppressionsByPath(supportStack, '/cross-region-stack-12345678901:us-east-1/Default/CrossRegionCodePipelineReplicationBucket/Resource', [
  {
    id: 'AwsSolutions-S1',
    reason: 'Artifact Bucket created by default by CDK to store the Artifacts.',
  },
]);
```

**Comment by msaavedra-earnd** [comment]
Should I do anything additional? I am adding it that way and also using `Stack.of` `const app = Stack.of(this)` and I get this error:
```
/Users/msaavedra/earnd/earnd_shared_infrastructure/.iac/node_modules/constructs/src/construct.ts:128
      throw new Error(`No child with id: '${id}'`);
            ^
Error: No child with id: 'cross-region-stack-502603844105:us-east-1'
```

**Comment by dontirun** [comment]
Can you share a code snippet the reproduces your application setup?
