### ISSUE TITLE
Ensure EBS is in backup plan

### ISSUE THREAD

**Issue by jen-rich** [cdklabs/cdk-nag#132]
*Control ID:*
CP-9(b)/CP-10/SI-12

*AWS Config Rule:* 
ebs-in-backup-plan

*Story:*
As an AWS consultant
I would like to check if my EBS resource configuration is compliant (encrypted in KMS)
So that I can check if my application conforms with Control IDs CP-9(b), CP-10, and SI-12 within NIST 800-53.

*Acceptance Criteria:*

    * Given a CDK stack with a *non-compliant EBS* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EBS resource for Control IDs CP-9(b), CP-10, and SI-12 within NIST 800-53 .
    * Given a CDK stack with a *compliant EBS* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53.
    * Given a CDK stack *without a EBS* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53

**Comment by dontirun** [comment]
Added to `NIST 800-53`  'Excluded Rules'  in the RULES file
