### ISSUE TITLE
Ensure EBS snapshot is able to be publicly restored

### ISSUE THREAD

**Issue by jen-rich** [cdklabs/cdk-nag#133]
*Control ID:*
AC-3/AC-4/AC-6/AC-21(b)/SC-7/SC-7(3)

*AWS Config Rule:* 
ebs-snapshot-public-restorable-check

*Story:*
As an AWS consultant
I would like to check if my EBS snapshot configuration is compliant (publicly restorable)
So that I can check if my application conforms with Control IDs AC-3, AC-4, AC-6, AC-21(b), SC-7, and SC-7(3) within NIST 800-53.

*Acceptance Criteria:*

    * Given a CDK stack with a *non-compliant EBS* snapshot
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EBS snapshot for Control IDs AC-3, AC-4, AC-6, AC-21(b), SC-7, and SC-7(3) within NIST 800-53 .
    * Given a CDK stack with a *compliant EBS* snapshot and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53.
    * Given a CDK stack *without a EBS* snapshot and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53

**Comment by dontirun** [comment]
Added to `NIST 800-53`  'Excluded Rules'  in the RULES file
