### ISSUE TITLE
bug: AwsSolutions-EC26 false positive when ec2 instance `requireImdsv2` is set to true

### ISSUE THREAD

**Issue by fiserv-plat-eng** [cdklabs/cdk-nag#1330]
### What is the problem?

`AwsSolutions-EC26` warning is triggered when adding `requireImdsv2` to an ec2 instance with all values with `encrypted: true`

### Reproduction Steps

Add the following test to `test/rules/EC2.test.ts`

```diff
diff --git a/test/rules/EC2.test.ts b/test/rules/EC2.test.ts
index ad14948..97d75d4 100644
--- a/test/rules/EC2.test.ts
+++ b/test/rules/EC2.test.ts
@@ -973,5 +973,20 @@ describe('Amazon Elastic Block Store (EBS)', () => {
       });
       validateStack(stack, ruleId, TestType.COMPLIANCE);
     });
+    test('Compliance 5 - Instance', () => {
+      new Instance(stack, 'Instance1', {
+        vpc: new Vpc(stack, 'Vpc'),
+        instanceType: new InstanceType(InstanceClass.T3),
+        machineImage: MachineImage.latestAmazonLinux2(),
+        blockDevices: [
+          {
+            deviceName: 'device',
+            volume: BlockDeviceVolume.ebs(1, { encrypted: true }),
+          },
+        ],
+        requireImdsv2: true,
+      });
+      validateStack(stack, ruleId, TestType.COMPLIANCE);
+    });
   });
 });
```

### What did you expect to happen?

No findings

### What actually happened?

Following warnings are returned 

```json
[{"entry": {"data": "AwsSolutions-EC26: The resource creates one or more EBS vol...."}}]
```

### cdk-nag version

2.27.33

### Language

Typescript

**Comment by fiserv-plat-eng** [comment]
After debugging this i looks like `CfnLaunchTemplate` will be created when setting `requireImdsv2` to true.

`CfnLaunchTemplate` forces `httpTokens` to be required but `blockDeviceMappings` is undefined:

```json
{"metadataOptions":{"httpTokens":"required"}}
```

**Comment by clueleaf** [comment]
It seems like the reason a `CfnLaunchTemplate` is created is the [current limitation of CloudFormation](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/655).
MetaData cannot be added to the instance directly using CloudFormation, and CDK uses launch templates as a workaround to enable IMDSv2.

**Comment by clueleaf** [comment]
Instead of checking `blockDeviceMappings` of every `CfnLaunchTemplate`, we can check launch templates that are actually used by EC2 instances or AutoScaling groups only.
