### ISSUE TITLE
use cdk-nag in unit test (jest)

### ISSUE THREAD

**Issue by pharindoko** [cdklabs/cdk-nag#1434]
### Describe your issue?

I tried to use cdk-nag in the unit tests in jest and had a look at this blog: 
https://aws.amazon.com/blogs/devops/manage-application-security-and-compliance-with-the-aws-cloud-development-kit-and-cdk-nag/

I used the example described in the blog under "Unit Testing with the AWS CDK Assertions Library" and updated the code to fit to my tests but it doesn`t return back any errors or warnings ? The test are successful.

When I add cdk-nag to my default bin/stack.ts and do a `cdk synth` it works as expected and I get errors and warnings.

**How can I use cdk-nag in combination with cdk test using jest ?**
**Does someone have a working sample or can agree that this is working as describe in the blog ?**

**Comment by dontirun** [comment]
Can you share a code snippet with your tests? 

Here's an [example](https://github.com/dontirun/state-machine-semaphore/blob/main/test/CdkNag.test.ts) of a similar setup (sightly different since it's a construct versus a stack)

**Comment by pharindoko** [comment]
Hey @dontirun 

thanks for the reply.
This is the unittest I use.

```typescript
import { App, Aspects, Stack } from "aws-cdk-lib";
import { Annotations, Match } from "aws-cdk-lib/assertions";
import { AwsSolutionsChecks } from "cdk-nag";
import { ClusterStack } from "../lib/cluster";
import { CronjobEntity } from "../lib/cronjobs.entity";
import { ScheduledCronjobStack } from "../lib/scheduled-cronjob.stack";
import path = require("path");

describe("cdk-nag AwsSolutions Pack", () => {
    let stack: Stack;
    let app: App;
    beforeEach(() => {
        // GIVEN
        app = new App();
        const env = {
            account: "123456789012",
            region: "us-east-1",
        };
        stack = new Stack(app, "test", {
            env,
        });
        const clusterStack = new ClusterStack(stack, "Cluster", {
            vpcId: "vpc-123456789",
            clusterName: "test",
            stage: "test",
            env,
        });

        const cronjobs: CronjobEntity = {
            directory: path.join(__dirname, "../../backend"),
            dockerfile: "./BatchProgs/TestCronjob/cronjob.Dockerfile",
            serviceName: "cronjob-test",
            eventSchedule: "rate(1 minute)",
            environmentVariables: {
                TEST: "test1",
            },
            cpu: 512,
            memoryLimitMiB: 1024,
        };

        new ScheduledCronjobStack(stack, "ScheduledCronjobStack", {
            cluster: clusterStack.cluster,
            vpcId: "vpc-123456789",
            subnetId: "subnet-123456789",
            cronjobEntity: cronjobs,
            stage: "test",
            env,
        });

        // WHEN
        Aspects.of(stack).add(new AwsSolutionsChecks());
    });

    // THEN
    test("No unsuppressed Warnings", () => {
        const warnings = Annotations.fromStack(stack).findWarning(
            "*",
            Match.stringLikeRegexp("AwsSolutions-.*")
        );
        expect(warnings).toHaveLength(0);
    });

    test("No unsuppressed Errors", () => {
        const errors = Annotations.fromStack(stack).findError(
            "*",
            Match.stringLikeRegexp("AwsSolutions-.*")
        );
        expect(errors).toHaveLength(0);
    });
});

```

**result:**
![image](https://github.com/cdklabs/cdk-nag/assets/5619511/4df4661a-4dd4-49b6-b2d4-711283fccc66)

**expected:** 
No unsurpressed Errors fails due to 4 errors found when I do 'cdk synth'

**Comment by dontirun** [comment]
>.findWarning


In your case you have several nested stacks (`ClusterStack`, `ScheduledCronJobStack`). The annotations for those nested stacks will not be present on the root stack (which is what you are checking for Annotations).

You'll have to check each stack individually, for example `Annotations.fromStack(clusterStack)`

**Comment by pharindoko** [comment]
will try - thanks for the hint!

**Comment by pharindoko** [comment]
ok this works as expected - thanks @dontirun !
