### ISSUE TITLE
Cannot detect any warnings or errors when running cdk synth

### ISSUE THREAD

**Issue by hageyahhoo** [cdklabs/cdk-nag#1524]
### General Issue

I would like to detect non-compliant warnings or errors by running `cdk synth` but it doesn't work.

### The Question

I tried to use cdk-nag based on the following blog post:
https://aws.amazon.com/blogs/devops/manage-application-security-and-compliance-with-the-aws-cloud-development-kit-and-cdk-nag/

I tried to reproduce S3 non-compliant errors by following `Walkthrough` section, but I could not see any errors when I run `cdk synth`. There were no error messages on the console. Additionally, csv file was not created on cdk.out. Moreover, there were no information about cdk-nag on template.json file.

On the other hands, unit test detected errors as expected based on `Advanced usage and further reading` section. The detected errors by unit test are as follows:
- AwsSolutions-S1: The S3 Bucket has server access logs disabled.
- AwsSolutions-S10: The S3 Bucket or bucket policy does not require requests to use SSL.

Am I missing something to run cdk synth?

### cdk-nag version

2.27.205

### Language

Typescript

### Other information

Here are information about my environment:
- Mac
    - OS: macOS Ventura 13.6
    - CPU: Intel Core i5 (2 GHz QuadCore)
- AWS CLI: 2.11.25
- CDK CLI: 2.111.0

**Comment by dontirun** [comment]
Can you provide a code sample where it is not working as expected? Specifically where you are initializing the cdk application with cdk-nag

**Comment by hageyahhoo** [comment]
Hi @dontirun 
Thank you for your quick reply.

Here is the target code to test.
```TypeScript
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Bucket } from 'aws-cdk-lib/aws-s3';

export class CdkTestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    const bucket = new Bucket(this, 'Bucket')
  }
}
```

And here is the unit test code.
```TypeScript
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { App, Aspects, Stack } from 'aws-cdk-lib';
import { AwsSolutionsChecks } from 'cdk-nag';
import { CdkTestStack } from '../lib/cdk_test-stack';

describe('cdk-nag AwsSolutions Pack', () => {
    let stack: Stack;
    let app: App;
    beforeAll(() => {
        // GIVEN
        app = new App();
        stack = new CdkTestStack(app, 'test');

        // WHEN
        Aspects.of(stack).add(new AwsSolutionsChecks());
    });

    // THEN
    test('No unsuppressed Warnings', () => {
        const warnings = Annotations.fromStack(stack).findWarning(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*')
        );
        expect(warnings).toHaveLength(0);
    });

    test('No unsuppressed Errors', () => {
        const errors = Annotations.fromStack(stack).findError(
            '*',
            Match.stringLikeRegexp('AwsSolutions-.*')
        );
        // It detects AwsSolutions-S1 and AwsSolutions-S10 errors here.
        expect(errors).toHaveLength(0);
    });
});
```

**Comment by dontirun** [comment]
Can you provide the code where you are initializing your CDK `App` and creating the stack?

**Comment by hageyahhoo** [comment]
@dontirun 

Here it is (located on bin directory as `cdk_test.ts`)
```TypeScript
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { CdkTestStack } from '../lib/cdk_test-stack';

const app = new cdk.App();
new CdkTestStack(app, 'CdkTestStack', {
});
```

Additionally, here is the file structure I've been trying.
- CdkTest
    - bin/cdk_test.ts
    - lib/cdk_test-stack.ts
    - test/cdk_test.test.ts

**Comment by dontirun** [comment]
You haven't added any `NagPack`s to your application. Here is an example for adding the AWS Solutions `NagPack` to your application

```ts
import * as cdk from 'aws-cdk-lib'; 
import { CdkTestStack } from '../lib/cdk_test-stack'; 
import { AwsSolutionsChecks } from 'cdk-nag' ;
import { Aspects } from 'aws-cdk-lib'; const app = new cdk.App(); 
Aspects.of(app).add(new AwsSolutionsChecks({  })) 
```

**Comment by hageyahhoo** [comment]
@dontirun 
Thanks for your correction! It worked as expected!

<img width="1351" alt="cdk-nag-worked" src="https://github.com/cdklabs/cdk-nag/assets/3157079/748c2a6f-ab71-48b7-b912-4b2abcd0174c">

I understood that I read the file name `bin/cdk_test.ts` as `test/cdk_test.test.ts` incorrectly on [this blog](https://aws.amazon.com/blogs/devops/manage-application-security-and-compliance-with-the-aws-cloud-development-kit-and-cdk-nag/).

Thanks for taking your time.
