### ISSUE TITLE
bug: spurious AwsSolutions-SMG4 with aws-cdk-lib >= 2.116.0

### ISSUE THREAD

**Issue by anentropic** [cdklabs/cdk-nag#1560]
### What is the problem?

we updated our version of aws-cdk-lib today from 2.115 to 2.120 latest

started getting this nag:

> AwsSolutions-SMG4: The secret does not have automatic rotation scheduled. AWS Secrets Manager can be configured to automatically rotate the secret for a secured service or database.

but in our cdk code there is clearly a rotation set up

### Reproduction Steps

```python
        rds_instance = rds.DatabaseInstance(
            ...
        )
        rds_instance.add_rotation_single_user(
            automatically_after=Duration.days(30),
            rotate_immediately_on_update=True,
        )
```

then use aws-cdk-lib >= 2.116.0

### What did you expect to happen?

no nag, because we have a rotation

### What actually happened?

when upgrading aws-cdk-lib to 2.116.0 or later we start getting the nag

### cdk-nag version

2.28.7

### Language

Python

### Other information

Looking at the changes released in aws-cdk-lib 2.116.0 there were two possibly relevant PRs:
- https://github.com/aws/aws-cdk/pull/28379
- https://github.com/aws/aws-cdk/pull/28303

I think it may be the latter, because [here](https://github.com/aws/aws-cdk/pull/28303/files#diff-fbedfd1e243b3f92b385c256860877d3b8600d9c2dd2b5286f227a9270c236f3L140) it changes the `rotationRules` in the generated schedule to use a `scheduleExpression` rather than `automaticallyAfterDays`

and the relevant check in cdk-nag: https://github.com/cdklabs/cdk-nag/blob/7e9aa43b300e71fa01ccebd639ae8de67feaaed7/src/rules/secretsmanager/SecretsManagerRotationEnabled.ts#L120 only looks for `automaticallyAfterDays` rather than any valid scheduling rule

**Comment by ruvimrd** [comment]
Related to #1565 and #1566

**Comment by clueleaf** [comment]
@anentropic Please try cdk-nag v2.28.13
