### ISSUE TITLE
Need the compliance and non-compliance test cases for the typescript-cdk rules

### ISSUE THREAD

**Issue by csubhras** [cdklabs/cdk-nag#1575]
### General Issue

https://github.com/cdklabs/cdk-nag/blob/main/RULES.md#errors

### The Question

We are looking for compliance and non-compliance test cases for the below rules , unable to find details in the github.

**- **Rule ID****        AwsSolutions-VPC7   
**- Cause**              The VPC does not have an associated Flow Log.
**- Explanation**      VPC Flow Logs capture network flow information for a VPC, subnet, or network interface and stores it in Amazon CloudWatch Logs. Flow log data can help customers troubleshoot network issues; for example, to diagnose why specific traffic is not reaching an instance, which might be a result of overly restrictive security group rules.

### cdk-nag version

CDK V2

### Language

Typescript

**Comment by dontirun** [comment]
Closing this in favor of https://github.com/cdklabs/cdk-nag/issues/1574
