### ISSUE TITLE
Need the compliance and non-compliance test cases for the typescript-cdk rulesshort issue description

### ISSUE THREAD

**Issue by csubhras** [cdklabs/cdk-nag#1580]
### General Issue

https://github.com/cdklabs/cdk-nag/blob/main/RULES.md#errors

### The Question

We are looking for compliance and non-compliance test cases for the below rules , unable to find details in the github.

**- Rule ID** AwsSolutions-EVB1
**- Cause** The event bus policy allows for open access.
**- Explanation** An open policy ("*" principal without a condition) grants anonymous access to an event bus. Use a condition to limit the permission to accounts that fulfill a certain requirement, such as being a member of a certain AWS organization.

### cdk-nag version

CDK V2

### Language

Typescript

**Comment by dontirun** [comment]
@csubhras please continue the conversation here https://github.com/cdklabs/cdk-nag/issues/1574

instead of opening a new issue for each of these
