### ISSUE TITLE
doc: AwsSolutions-CFR6 conflicts with AWS recommendation

### ISSUE THREAD

**Issue by EysaN** [cdklabs/cdk-nag#1582]
Under [RULES.md](https://github.com/cdklabs/cdk-nag/blob/main/RULES.md), the rule AwsSolutions-CFR6 results in the following error when synthesizing CDK app:
` AwsSolutions-CFR6: The CloudFront distribution does not use an origin access identity with an S3 origin.`

However, [AWS Documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) clearly says: `We recommend using OAC` and it marks OAI as `legacy, not recommended`.

Currently, we have to manually suppress it to avoid synthesizing failure.

Could you please support OAC instead?

**Comment by dontirun** [comment]
@EysaN I'll take a look into what needs to be done for this one. Thanks for bringing it up!

**Comment by clueleaf** [comment]
I think we can check if `OriginAccessControlId` is configured in CloudFront origin.
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#cfn-cloudfront-distribution-origin-originaccesscontrolid

**Comment by dontirun** [comment]
I think there will need to be a few changes here

## Streaming Distribution
CloudFront Streaming distributions[ don't seem  to support](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-streamingdistribution-streamingdistributionconfig.html)` OAC`s so the rule should be kept the same for Streaming Distributions

## Distribution

@clueleaf  I think you're correct that we need to  check the `OriginAccessControlId` property on Distributions.  Additionally, if the `OAC` is created in the stack, we should also check if the [SigningBehavior](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html#cfn-cloudfront-originaccesscontrol-originaccesscontrolconfig-signingbehavior) isn't set to `never`

**Comment by braidoa** [comment]
Hi. Commenting from AWS ProServe Engagement Security:
We will wait until cdk-nag is updated, and then we'll update our guidance to ProServe builders. 😄

**Comment by clueleaf** [comment]
Since currently [we have to use `addPropertyOverride` to configure OAC](https://github.com/aws/aws-cdk/issues/21771#issuecomment-1479659999), and [cdk-nag can not see overridden properties](https://github.com/cdklabs/cdk-nag?tab=readme-ov-file#rules-and-property-overrides), I don't think supporting OAC is possible now.
Waiting for an L2 construct for OAC. (https://github.com/aws/aws-cdk/issues/21771 https://github.com/aws/aws-cdk-rfcs/issues/617)
