### ISSUE TITLE
Exported rules aren't typed correctly

### ISSUE THREAD

**Issue by MagnusHJensen** [cdklabs/cdk-nag#1701]
### General Issue

Exported rules aren't typed correctly

### The Question

We are using cdk-nag for some s3 rules, to keep our infrastructure safe by checking it.

However when we import the rules, the type definitions is `any`, and we therefore have to cast the rule ourselves to the correct type.

I would assume the type used when creating the rule `(node: CfnResource) => NagRuleCompliance` would also be the type of the default export in the individual rule files.

An example is `S3BucketLevelPublicAccessProhibited`: 
- The current type file looks like this:
```ts
declare const _default: any;
/**
 * S3 Buckets prohibit public access through bucket level settings
 * @param node the CfnResource to check
 */
export default _default;
```

I would have expected the type file to look like this:
```ts
declare const _default: (node: CfnResource) => NagRuleCompliance;
/**
 * S3 Buckets prohibit public access through bucket level settings
 * @param node the CfnResource to check
 */
export default _default;
```

Which would also align with the initial typescript implementation:
https://github.com/cdklabs/cdk-nag/blob/c8ceb1dda24df668ab5395dcf720815aa73033c9/src/rules/s3/S3BucketLevelPublicAccessProhibited.ts#L14-L15

### cdk-nag version

2.27.127

### Language

Typescript

**Comment by dontirun** [comment]
Definitely a bug, thanks for reporting!

> However when we import the rules, the type definitions is any, and we therefore have to cast the rule ourselves to the correct type

What does your `tsconfig` look like? The following works for me without needing to do any casting.

```ts
import * as cdk from 'aws-cdk-lib';
import { Aspects, CfnResource } from 'aws-cdk-lib';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import {
  NagMessageLevel,
  NagPack,
  NagPackProps,
  rules,
} from 'cdk-nag';
import { Construct, IConstruct } from 'constructs';

const app = new cdk.App();
export class ExampleChecks extends NagPack {
  constructor(props?: NagPackProps) {
    super(props);
    this.packName = 'Example';
  }
  public visit(node: IConstruct): void {
    if (node instanceof CfnResource) {
      // premade rule
      this.applyRule({
        info: 'My brief info.',
        explanation: 'My detailed explanation.',
        level: NagMessageLevel.ERROR,
        rule: rules.lambda.LambdaLatestVersion,
        node: node,
      });
    }
  }
}

export class TestStack extends cdk.Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new Function(this, 'Test', {
      runtime: Runtime.PYTHON_2_7,
      code: Code.fromInline('foo'),
      handler: 'main.handler',
    });
  }
}

new TestStack(app, 'TestStack');

Aspects.of(app).add(new ExampleChecks({ verbose: true }));
```

**Comment by MagnusHJensen** [comment]
Hmm, interesting.

Now looking at the typedef imported it is correct, but the version seems to be the same.
Unsure what has gone wrong in the process, or what has changed haha.
