### ISSUE TITLE
remove CodeBuildProjectPrivilegedModeDisabled rule

### ISSUE THREAD

**Issue by clueleaf** [cdklabs/cdk-nag#1803]
### General Issue

Remove CodeBuildProjectPrivilegedModeDisabled rule

### The Question

Security Hub retired `CodeBuild.5` rule, stating `Enabling privileged mode in a CodeBuild project does not impose an additional risk to the customer environment.`
`[CodeBuild.5] CodeBuild project environments should not have privileged mode enabled`
https://docs.aws.amazon.com/securityhub/latest/userguide/controls-change-log.html

`CodeBuildProjectPrivilegedModeDisabled` implemented as `AwsSolutions-CB3` should be removed accordingly.

### cdk-nag version

2.29.0

### Language

Typescript

**Comment by dontirun** [comment]
Yes, this rule should be removed
