### ISSUE TITLE
remove AthenaWorkgroupEncryptedQueryResults rule

### ISSUE THREAD

**Issue by clueleaf** [cdklabs/cdk-nag#1804]
### General Issue

Remove AthenaWorkgroupEncryptedQueryResults rule

### The Question

Security Hub retired `Athena.1` rule, stating `Amazon S3 now provides default encryption with S3 managed keys (SS3-S3) on new and existing S3 buckets.`
`[Athena.1] Athena workgroups should be encrypted at rest`
https://docs.aws.amazon.com/securityhub/latest/userguide/controls-change-log.html

`AthenaWorkgroupEncryptedQueryResults` implemented as `AwsSolutions-ATH1` should be removed accordingly.

### cdk-nag version

2.29.0

### Language

Typescript

**Comment by dontirun** [comment]
Yes agreed, this rule should be removed
