### ISSUE TITLE
remove SNSEncryptedKMS rule

### ISSUE THREAD

**Issue by clueleaf** [cdklabs/cdk-nag#1805]
### General Issue

Remove SNSEncryptedKMS rule

### The Question

Security Hub retired `SNS.1` rule, stating `By default, SNS encrypts topics at rest with disk encryption. For more information, see [Data encryption](https://docs.aws.amazon.com/sns/latest/dg/sns-data-encryption.html). Using AWS KMS to encrypt topics is no longer recommended as a security best practice.`
`[SNS.1] SNS topics should be encrypted at-rest using AWS KMS`
https://docs.aws.amazon.com/securityhub/latest/userguide/controls-change-log.html

`SNSEncryptedKMS` implemented as `AwsSolutions-SNS2` should be removed accordingly.

### cdk-nag version

2.29.0

### Language

Typescript

**Comment by dontirun** [comment]
Agreed, this rule should be removed
