### ISSUE TITLE
Ensure 2 tunnels for VPC-VPN connections

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#25]
*Control IDs:* 
CP-10

*Rulename:* 
vpc-vpn-2-tunnels-up

*Story:*
As an AWS developer
I would like to check if my VPC-VPN configuration is compliant (at least two redundant tunnels)
So that I can check if my application conforms with Control ID *CP-10*  within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant VPC-VPN tunnel* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant VPC-VPN tunnel resource for Control ID *CP-10* within NIST 800-53.
* Given a CDK stack with a *compliant VPC-VPN tunnel* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *CP-10* within NIST 800-53.
* Given a CDK stack *without a VPC-VPN tunnel* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *CP-10* within NIST 800-53.

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
