### ISSUE TITLE
Ensure encryption for EC2 EBS volumes is the default

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#26]
*Control IDs:* 
SC-28

*Rulename:* 
ec2-ebs-encryption-by-default

*Story:*
As an AWS developer
I would like to check if my EBS configuration is compliant (encrypted by default)
So that I can check if my application conforms with Control ID *SC-28* within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant EBS* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EBS resource for Control ID *SC-28* within NIST 800-53.
* Given a CDK stack with a *compliant EBS* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *SC-28* within NIST 800-53.
* Given a CDK stack *without an EBS* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *SC-28* within NIST 800-53.

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
