### ISSUE TITLE
Ensure DynamoDB tables are encrypted in KMS

### ISSUE THREAD

**Issue by jen-rich** [cdklabs/cdk-nag#32]
*Control ID:*
SC-13

*AWS Config Rule:* 
dynamodb-table-encrypted-kms

*Story:*
As an AWS consultant
I would like to check if my DynamoDB table configuration is compliant (encrypted in KMS)
So that I can check if my application conforms with Control ID SC-13 within NIST 800-53.

*Acceptance Criteria:*

    * Given a CDK stack with a *non-compliant DynamoDB* table
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant DynamoDB table for Control ID SC-13 within NIST 800-53 .
    * Given a CDK stack with a *compliant DynamoDB* table and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53.
    * Given a CDK stack *without a DynamoDB* table and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
