### ISSUE TITLE
publish Java JSII package

### ISSUE THREAD

**Issue by thomasklinger1234** [cdklabs/cdk-nag#357]
Hey,

I just wanted to wrap cdk-nag into our existing CDK aspect collection and expose it to our users. We publish NPM and Maven packages currently (built with JSII). However, cdk-nag does not have Java enabled. Is this something on your roadmap?

**Comment by dontirun** [comment]
Hi there! Thanks for the feedback. This is something that we are currently looking into 😄

**Comment by dontirun** [comment]
Keep

**Comment by dontirun** [comment]
Resolved by #682 #683
