### ISSUE TITLE
Ensure public access to lambda functions is prohibited

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#38]
*Control IDs:* 
AC-3, AC-4, AC-6, AC-21(b), SC-7, SC-7(3)

*Rulename:* 
lambda-function-public-access-prohibited

*Story:*
As an AWS developer
I would like to check if my lambda configuration is compliant (public access prohibited)
So that I can check if my application conforms with Control IDs *AC-3, AC-4, AC-6, AC-21(b), SC-7, SC-7(3)* within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant lambda function*
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant lambda resource for Control IDs *AC-3, AC-4, AC-6, AC-21(b), SC-7, SC-7(3)* within NIST 800-53 .
* Given a CDK stack with a *compliant lambda function* and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *AC-3, AC-4, AC-6, AC-21(b), SC-7, SC-7(3)* within NIST 800-53.
* Given a CDK stack *without a lambda function* and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *AC-3, AC-4, AC-6, AC-21(b), SC-7, SC-7(3)* within NIST 800-53.

**Comment by dontirun** [comment]
Added to NIST 800-53 'Excluded Rules' in the RULES file
