### ISSUE TITLE
Ignore S1 rule not working

### ISSUE THREAD

**Issue by sholtomaud** [cdklabs/cdk-nag#396]
Hello there, I cannot see how to apply ignore the S1 rule on an S3 bucket. 

If I add another logging bucket the S1 rule Errors on that bucket, etc. 

Could you provide an example of how to ignore on S3 buckets?

**Comment by dontirun** [comment]
@ashemedai You are correct, thanks for commenting on this issue! 

I can personally attest to the fact that having the logging bucket log to itself 
 causes an infinite loop of logging 😅.

So for those looking at this now, you should suppress  the violation on the logging bucket
