### ISSUE TITLE
feat: aws-cdk v2 support

### ISSUE THREAD

**Issue by relm923** [cdklabs/cdk-nag#428]
### Description

Any plans to add support for aws-cdk v2 (https://www.npmjs.com/package/aws-cdk-lib)?

https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html

### Use Case

Cdk is migrating to v2 (similar to `monocdk`) but the current versions of this library do not support the updated v2 Construct 

### Proposed Solution

Add full support for cdk v2

### Other information

https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
Note for tracking. It does not look like it is currently as simple as doing some regex replacements like the cdk -> monocdk process for building.

```bash
find ./src -type f | xargs sed -i  's,@aws-cdk/core,aws-cdk-lib,g'
find ./test -type f | xargs sed -i  's,@aws-cdk/core,aws-cdk-lib,g'
find ./src -type f | xargs sed -i  's,@aws-cdk,aws-cdk-lib,g'
find ./test -type f | xargs sed -i  's,@aws-cdk,aws-cdk-lib,g'
find ./test -type f | xargs sed -i  's,aws-cdk-lib/assert,@aws-cdk/assert,g'
```

The above regex will capture most of what needs to be done but fail to capture the following cases

1. `IConstruct` is part of `constructs` not `aws-cdk-lib`
2.  Some constructs that have L2s in cdk and monocdk don't have equivalent L2s in cdk v2 which breaks some of the testing. For example `aws-cdk-lib/aws-msk` does not have `Cluster`, `KafkaVersion`, and `ClientBrokerEncryption` which is [used in testing](https://github.com/cdklabs/cdk-nag/blob/4037e7c0279d2ffeba0b89da20d842e55482d206/test/AwsSolutions/AwsSolutionsAnalytics.test.ts#L27).  This is a unknown that could cause breaks in builds when new services are added as well
