### ISSUE TITLE
cdk-nag with python.

### ISSUE THREAD

**Issue by mrpackethead** [cdklabs/cdk-nag#442]
### General Issue

cdk-nag with python.

### The Question

If im using a non ts code ( python ) is it possible for me to add my own rules?   and remove rules from the rule sets that already exisit? 

### cdk-nag version

current

### Language

Python

**Comment by dontirun** [comment]
Multipart answer

1. While cdk-nag can be used with python cdk applications, the rules are written in typescript
2. cdk-nag has a way to [suppress specific rules](https://github.com/cdklabs/cdk-nag#suppressing-a-rule) that you do not wish to enforce
3. The prebuilt cdk-nag does not currently have a way to import locally written rules into it. Currently the only way to add in your own rules is to clone the repository and/subtract from existing packs or build your own
4. cdk-nag is an extension of the CDK [Aspect sytem](https://docs.aws.amazon.com/cdk/latest/guide/aspects.html). If there are only specific things that you want to test for, you can write Aspects in python and apply them to your application for a similar result. [This blogpost](https://aws.amazon.com/blogs/devops/align-with-best-practices-while-creating-infrastructure-using-cdk-aspects/) goes into more details about writing your own aspects

Hope this helps!
