### ISSUE TITLE
feat: rules are exported

### ISSUE THREAD

**Issue by webratz** [cdklabs/cdk-nag#482]
### Description

We have a custom set of requirements, but many of the already implemented rules are already super helpful.
Sadly the rules are not exported, so one would have to either copy them or implement them on your own.

### Use Case

We have a custom set of rules that apply within our company. So we want to build a custom internal rule pack, combined of custom rules and already existing ones.

### Proposed Solution

Export the rules, or make them available in a separate package.

### Other information

Currently using the newly release v2 compatible version

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
From what I understand you would like to

1. Create your own `NagPack` on an as needed basis without the need for rebuilding the package
2. Pull from the existing rules and apply them to the `NagPack`
3. Create your own rules and apply them to the `NagPack`

Is that correct?

The drawback with this approach is that unless you build your own package, it would be difficult to scale this across multiple applications without re-implementing the rule additions on each application (though it could be as simple as a copy and paste of the class)

That being said, it could be a good opportunity to move the [rule creation helper methods](https://github.com/cdklabs/cdk-nag/blob/fc05f0f05f39120af22a988e012b9317bab04626/src/nag-pack.ts#L215) to a package with the rules.

**Comment by webratz** [comment]
Yes that is correct.
Also the plan is not to have it per application, but we use a shared cdk lib within the company that takes care of the checks, so we only implement it in one place.

I found another variant to achieve something similar:
I'm adding eg the NagPack provided by cdk-nag, but also add an aspect to add suppressions for rules that are not important / relevant for my organization. With that all new rules added would be auto enabled, which can be good to increase coverage, but of course also lead to new rules added that should have been hidden for my org.
