### ISSUE TITLE
Check that IMDSV2 is enabled on EC2 resources

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#53]
*Control ID:*
AC-6

*AWS Config Rule:* 
ec2-imdsv2-check

*Story:*
As an AWS consultant
I would like to check if my EC2 configuration is compliant (Instance Metadata Service Version 2 (IMDSv2)  enabled)
So that I can check if my application conforms with Control ID *AC-6* within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant EC2* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EC2 resource for Control ID *AC-6* within NIST 800-53.
* Given a CDK stack with a *compliant EC2* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *AC-6* within NIST 800-53.
* Given a CDK stack *without an EC2* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control ID *AC-6* within NIST 800-53.

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
