### ISSUE TITLE
NIST 800.53 Ensure managed EC2 instances are complaint with their association

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#56]
*Control IDs:* 
CM-2, CM-7(a), CM-8(3)(a), SI-2(2)

*Rulename:* 
ec2-managedinstance-association-compliance-status-check

*Story:*
As an AWS developer
I would like to check if my EC2 configuration is compliant with association standards.
So that I can check if my application conforms with Control IDs *CM-2, CM-7(a), CM-8(3)(a), SI-2(2)* within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant EC2* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EC2 resource for Control IDs *CM-2, CM-7(a), CM-8(3)(a), SI-2(2)* within NIST 800-53 .
* Given a CDK stack with a *compliant EC2* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *CM-2, CM-7(a), CM-8(3)(a), SI-2(2)* within NIST 800-53.
* Given a CDK stack *without an EC2* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *CM-2, CM-7(a), CM-8(3)(a), SI-2(2)* within NIST 800-53.

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
