### ISSUE TITLE
NIST 800.53 Ensure managed EC2 instances are compliant with their patches

### ISSUE THREAD

**Issue by alex174** [cdklabs/cdk-nag#57]
*Control IDs:* 
SI-7(1), SI-2(2), CM-8(3)(a)

*Rulename:* 
ec2-managedinstance-patch-compliance-status-check

*Story:*
As an AWS developer
I would like to check if my EC2 configuration is compliant with patch requirements
So that I can check if my application conforms with Control IDs *SI-7(1), SI-2(2), CM-8(3)(a)* within NIST 800-53.

*Acceptance Criteria:*

* Given a CDK stack with a *non-compliant EC2* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EC2 resource for Control IDs *SI-7(1), SI-2(2), CM-8(3)(a)* within NIST 800-53.
* Given a CDK stack with a *compliant EC2* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *SI-7(1), SI-2(2), CM-8(3)(a)* within NIST 800-53.
* Given a CDK stack *without an EC2* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about Control IDs *SI-7(1), SI-2(2), CM-8(3)(a)* within NIST 800-53.

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
