### ISSUE TITLE
doc: suppression examples would be better using List[NagPackSuppression]

### ISSUE THREAD

**Issue by mrgum** [cdklabs/cdk-nag#583]
### Describe your issue?

The suppression examples use List[dict] rather than List[NagPackSuppression]

For example "Example 1) Default Construct" has

NagSuppressions.add_resource_suppressions(test, [id="AwsSolutions-EC23", reason="lorem ipsum"])

when

NagSuppressions.add_resource_suppressions(test, [NagPackSuppression(id="AwsSolutions-EC23", reason="lorem ipsum")])

would seem to be better

I'd be happy to spend the time changing these if its accepted

**Comment by mrgum** [comment]
Hello

https://constructs.dev/packages/cdk-nag/v/2.4.39?lang=python#suppressing-a-rule

But the typescript version shows the same issue
https://constructs.dev/packages/cdk-nag/v/2.4.39?lang=typescript#suppressing-a-rule

No mention of NagPackSuppression

**Comment by dontirun** [comment]
That is a valid example for TypeScript since the `NagPackSuppression` [type is inferred](https://www.typescriptlang.org/docs/handbook/2/objects.html#optional-properties). We would have to look to see if there are any ways to influence the python documentation generated by jsii.

**Comment by mrgum** [comment]
Would asserting the type help the generation?
    NagSuppressions.addResourceSuppressions(test, [
      <NagPackSuppression>{
        id: 'AwsSolutions-EC23', reason: 'lorem ipsum'
      },
    ]);

**Comment by dontirun** [comment]
I think we would need to do something like this https://github.com/aws/jsii/issues/826
