### ISSUE TITLE
feat: More granular suppressions

### ISSUE THREAD

**Issue by tkglaser** [cdklabs/cdk-nag#634]
### Description

When suppressing a rule, I would like to be able to suppress the rule only for a certain section of the resource.

### Use Case

One example would be `AwsSolutions-IAM5`, which is triggered whenever there is a `*` anywhere in the policy. There are certain CDK methods, like `<dynamodbTable>.grantReadWriteData(myRole)` that add wildcard actions like `kms:ReEncrypt*`.
This will trigger the nag rule and if I suppress it, I will be unable to detect any other problems on this role that may arise in future.

### Proposed Solution

It should be possible to add metadata to rule suppressions that the rules can evaluate based on their specific needs. For example
```
NagSuppressions.addResourceSuppressions(myResource, [{
  id: 'AwsSolutions-IAM5'
  reason: 'Dynamo Table Access'
  metadata: {
    allowedActions: ['kms:ReEncrypt*']
  }
}]
```

I realise, that the metadata field will have a different structure for different rules, maybe this can be made type safe by the rule specifying an interface or some kind of validation.

Maybe we can even have a `NagSuppressionBuilder` that provides a fluent API for this?

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
This would be a cool feature to add in. A few initial thoughts/questions. By adding `allowedActions` are we 
1. Expanding the scope of the rule to allow for those actions (so not counted as a `suppression`) 
2. Generating a conditional `suppression`? The distinction matters especially when it comes to generating the `Compliance Reports`.

With the current system I think the  `1` is  certainly possible (though from a security reviewer perspective I don't think this is optimal). `2` doesn't currently seem possible without somehow adding functionality to the suppression system to start reading the rule (it would have to know exactly where to look in the Resource and what to parse). In the case of `2` it might be "easier" to use the programming language and if statements to conditionally apply the suppression. Would love to be wrong here though!

**Comment by tkglaser** [comment]
I'm not sure about writing an aspect that does a pre-check and then applies the suppression conditionally. To me, that defeats the purpose a little.

There is a third way I think.

Let's say that a rule is allowed to return either a simple `NagRuleCompliance` or an array of, let's call them `Finding`s. So for example `IAM5` would return instead of `NagRuleCompliance.NON_COMPLIANT` something like this:

```
[
  { nonCompliantAction: 'kms:ReEncrypt*' },
  { nonCompliantAction: 's3:*' },
]
```

This can show up in the reporting as two separate non-compliances against the same resource. Why not, right?

This change can be done in a backward compatible way, the rule engine would simply have to test if the return value of the rule is an array or not. So sure, `IAM5` needs to be rewritten for this example but all other rules can stay as they are.

Now, when it comes to suppressions, we could have the option to add a filter statement that is applied to that array of `Finding`s. That filter statement could be created in a very flexible way, [jmespath](https://jmespath.org/) comes to mind. The idea is to apply the suppression only to those findings that are in the filter set.

I wouldn't expect people to write jmespath queries so we could have helpers:
```
NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5',
  reason: 'Default Dynamo Actions from CDK',
  appliesTo: policyActions(['kms:ReEncrypt*']), // util that creates the relevant jmespath query
}]
```

The effect of this is that the suppression would only be applied to the first `Finding` in the example above but not the second. So I would still get a failure because of the `s3:*` which is exactly what I want.

**Comment by dontirun** [comment]
I like that! I think we could generalize to apply a similar approach could be applied to rules with `ports`, like [EC2RestrictedCommonPorts](https://github.com/cdklabs/cdk-nag/blob/b44fae24523719c339718eb053ba0fa7c48f57db/src/rules/ec2/EC2RestrictedCommonPorts.ts#L10) or `log types` in [AuroraMySQLLogging](https://github.com/cdklabs/cdk-nag/blob/b44fae24523719c339718eb053ba0fa7c48f57db/src/rules/rds/AuroraMySQLLogging.ts#L22).

**Comment by tkglaser** [comment]
Yeah I think this could be used to solve all those cases where we want to report and suppress with a finer granularity. The rules engine doesn't need to know the structure of a `Finding` object, it simply runs the jmespath query and reports on whatever is left so it can be absolutely generic.

**Comment by tkglaser** [comment]
Another thought: Instead of the jmespath stuff, we could make it even easier and make the rule ids more like ARNs so they could be suppressed this this:
```
NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5::Action::kms:ReEncrypt*', // suppress for action 'kms:ReEncrypt*'
  reason: 'Default Dynamo Actions from CDK',
}])

NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5',   // Suppressing the whole rule would still work like before
  reason: 'All is correct',
}])

NagSuppressions.addResourceSuppressions(myInstance, [{
  id: 'SomePack-EC2RestrictedCommonPorts::Port::20',   // Suppressing the finding for port 20 only
  reason: 'Need that port for things',
}])
```

The string matching could be done with simple string prefix matching and maybe in future even allowing regexes.

What do you think?

**Comment by dontirun** [comment]
I like where the idea is going, but there are a few things to consider.

1. The ARN approach makes it very cumbersome to suppress multiple findings at once.
2. All suppressions get added to the resultant CloudFormation template metadata. Since templates have size limits, we should try to use as little space as possible when writing suppression data to the template.
With the ARN approach `2` could be mitigated with the Suppression API handing the metadata optimization on the backend at the cost of the API and metadata not being identical. That could be fine as long as it's not difficult for a human to write the same supersession, but it would be nice to avoid that if possible

Currently resource metadata looks like the following

```
      "Metadata": {
        "cdk_nag": {
          "rules_to_suppress": [
            {
              "id": "AwsSolutions-IAM5",
              "reason": "at least 10 characters"
            }
          ]
        }
```

With granular suppression it could look something like this
```
      "Metadata": {
        "cdk_nag": {
          "rules_to_suppress": [
            {
              "id": "AwsSolutions-IAM5",
              "applies_to": ["Action::kms:ReEncrypt*","Resource::foo"]
              "reason": "at least 10 characters"
            }
          ]
        }
```

it could also accept something like this as well (not too sure on this one)
```
      "Metadata": {
        "cdk_nag": {
          "rules_to_suppress": [
            {
              "id": "AwsSolutions-IAM5::Action::kms:ReEncrypt*",
              "applies_to": ["Resource::foo"]
              "reason": "at least 10 characters"
            }
          ]
        }
```

That might be reflected in the API like
```
NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5::Action::kms:ReEncrypt*', // suppress for action 'kms:ReEncrypt*'
  reason: 'Default Dynamo Actions from CDK',
}])

NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5::Action::kms:ReEncrypt*', // suppress for action 'kms:ReEncrypt*'
  applies_to: ['Resource::foo']
  reason: 'Default Dynamo Actions from CDK',
}])

NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5',   // Suppressing the whole rule would still work like before
  reason: 'All is correct',
}])

NagSuppressions.addResourceSuppressions(myInstance, [{
  id: 'SomePack-EC2RestrictedCommonPorts::Port::20',   // Suppressing the finding for port 20 only
  reason: 'Need that port for things',
}])
```

**Comment by tkglaser** [comment]
You make some excellent points and I like your suggestion of making the `appliesTo` a simple string array. It still covers all the use cases and is a whole lot easier. So, abandoning the ARN-like rule ids but keeping the string-array filters gives:
```
// API
NagSuppressions.addResourceSuppressions(myRole, [{
  id: 'AwsSolutions-IAM5, 
  appliesTo: ['Action::kms:ReEncrypt*', `Resource::${myBucket.arnForObjects('*')}`],
  reason: 'My Suppressions',
}])

// CFN
"Metadata": {
  "cdk_nag": {
    "rules_to_suppress": [
      {
        "id": "AwsSolutions-IAM5",
        "applies_to": ["Action::kms:ReEncrypt*", "Resource::arn:aws:s3:::mybucket/*"],
        "reason": "My Suppressions"
      }
    ]
  }
```
This is probably as tight as we can pack this while still being human-readable. The change to the rules engine should be easy too.

**Comment by dontirun** [comment]
> The change to the rules engine should be easy too.

Lets hope so 😄 . I think we're at a good state for implementation

**Comment by tkglaser** [comment]
Great! I'm happy to contribute this. Give me a few days and I'll post a PR.
