### ISSUE TITLE
feat: check for errors / warnings in construct tests.

### ISSUE THREAD

**Issue by webratz** [cdklabs/cdk-nag#728]
### Description

I want to have a test for each of my constructs in my (private) construct lib, that they do not violate any of the cdk-nag rules.

For that i came up with a simple test:

```ts
    function getTestAssets(props: SQSQueueProps) {
        const app = new App();
        const stack = new Stack(app, 'testStack');
        const resource = new SQSQueue(stack, 'testQueue', props);
        const template = Template.fromStack(stack);
        return { template, stack, app, resource };
    }

    test('Queue has no error annotations', () => {
        const { stack } = getTestAssets({});
        const annotations = Annotations.fromStack(stack);
        annotations.hasNoError('*', Match.anyValue());
    });
```

This works in general. But it has the downside of also alerting for rules that are suppressed.
I'm wondering if there is already a way where i could go through all cdk-nag rules of a Stack, similar to the `Annotations` but suppressed rules are not shown.
I searched a bit through the source code of this project, but I didn't see anything that would help with that obviously. But also I did not yet fully understand how the suppressions technically work.

### Use Case

Testing constructs to be compliant with the rules.

### Proposed Solution

Following the patterns of the `Annotations` in CDK sth like the following would be usable

```ts
const nags = Nags.fromStack(stack);
nags.hasNoError(path: '*', 'AwsSolutions-SMG4')
// or also with a Matcher
nags.hasNoError(path: '*', Match.anyValue())
```

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by webratz** [comment]
After reading through https://github.com/cadklabs/cdk-nag/blob/main/src/nag-pack.ts#L117 my understanding would be that actually no messages should be added if the rules are correctly suppressed.
I'll dive a bit deeper into that to figure out if my inital approach actually works, but there is maybe some other issue.

**Comment by dontirun** [comment]
Currently cdk-nag does not keep track of all the `Nags` that have occurred on a stack. It evaluates a rule on a per resource basis using Aspects and makes a decision on whether or not to apply a Warning or Error Annotation [based on Stack and Resource suppressions](https://github.com/cdklabs/cdk-nag/blob/c4c37c7eda191e56b688cac8af472d895e634949/src/utils/nag-suppression-helper.ts#L53). 

> This works in general. But it has the downside of also alerting for rules that are suppressed.
This depends on how you are suppressing the rules. You could suppress the rules in the Stack itself

```typescript
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Bucket } from 'aws-cdk-lib/aws-s3';
import { NagSuppressions } from 'cdk-nag'

export class CdkTestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);
    NagSuppressions.addStackSuppressions(this, [
      {
        id: 'AwsSolutions-S1',
        reason: 'Demonstrate a stack level suppression.'
      },
    ])
    const bucket = new Bucket(this, 'rBucket', { enforceSSL: true })
    NagSuppressions.addResourceSuppressions(bucket, [
      {
        id: 'AwsSolutions-S2',
        reason: 'Demonstrate a resource level suppression.'
      },
    ])
  }
}
```

Then create a test like the following to detect any unsuppressed rules. 

```typescript
import { Annotations, Match } from 'aws-cdk-lib/assertions';
import { App, Aspects, Stack } from 'aws-cdk-lib';
import { AwsSolutionsChecks } from 'cdk-nag';
import { CdkTestStack } from '../lib/cdk_test-stack';

describe('cdk-nag AwsSolutions Pack', () => {
  let stack: Stack;
  let app: App;
  beforeAll(() => {
    // GIVEN
    app = new App();
    stack = new CdkTestStack(app, 'test');

    // WHEN
    Aspects.of(stack).add(new AwsSolutionsChecks());
  });

  // THEN
  test('No unsuppressed Warnings', () => {
    const warnings = Annotations.fromStack(stack).findWarning(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*')
    );
    expect(warnings).toHaveLength(0);
  });

  test('No unsuppressed Errors', () => {
    const errors = Annotations.fromStack(stack).findError(
      '*',
      Match.stringLikeRegexp('AwsSolutions-.*')
    );
    expect(errors).toHaveLength(0);
  });
});

```

**Comment by webratz** [comment]
Thanks for the detailed answer. That approach works well for me.
