### ISSUE TITLE
AwsSolutions-EC23 only check for the CIDR and not the open ports

### ISSUE THREAD

**Issue by aruanurag** [cdklabs/cdk-nag#750]
### What is the problem?

AwsSolutions-EC23 rule fails if a security group is created with "0.0.0.0/0 on a specific port.
For example if a  security group is configured for a internet facing ALB it has a ingress rule defined as "allow traffic from 0.0.0.0/0 on port 80"  but cdk_nag marks it as non-compliant 

### Reproduction Steps

Create a security group ingress rule like 
`self.alb_security_group.add_ingress_rule(
            peer=ec2.Peer.any_ipv4(),
            connection=ec2.Port.tcp(80),
            description="Allows HTTP access from Internet to ALB"
        )`

### What did you expect to happen?

Analysis should not fail

### What actually happened?

Analysis failed

### cdk-nag version

2.10.2

### Language

Python

**Comment by dontirun** [comment]
Hey! This is the intended behavior for this specific rule. It will trigger on full open access to _any_ port. If you have a valid use case (such as a public internet facing load balancer intended for open access) that may be a good use case for using a Suppression

**Comment by anentropic** [comment]
I think that doesn't match the extended rule description here: https://github.com/cdklabs/cdk-nag/blob/main/RULES.md

> AwsSolutions-EC23 | The Security Group allows for 0.0.0.0/0 or ::/0 inbound access.
> Large port ranges, when open, expose instances to unwanted attacks. More than that, they make traceability of vulnerabilities very difficult. For instance, your web servers may only require 80 and 443 ports to be open, but not all. One of the most common mistakes observed is when all ports for 0.0.0.0/0 range are open in a rush to access the instance. EC2 instances must expose only to those ports enabled on the corresponding security group level.

**Comment by toxygene** [comment]
I came across this rule today and came to the same conclusion that @anentropic did -- the rule description seems to indicate a problem with the port ranges, not the CIDR. Furthermore, it appears that this rule is implementing the AWS Control Tower [CT.EC2.PR.3](https://docs.aws.amazon.com/controltower/latest/controlreference/ec2-rules.html#ct-ec2-pr-3-description) controls, but the rule specifically mentions it doesn't apply to ports 80 and 443.

I'd ask that you'd reconsider closing this ticket.
