### ISSUE TITLE
feat: Throw error if unused suppressions are found.

### ISSUE THREAD

**Issue by maclema** [cdklabs/cdk-nag#800]
### Description

Unused suppressions are a code stink and could lead to future unintended suppressions. If unused suppressions are discovered an error should be thrown.

### Use Case

Unused suppressions, especially for IAM policy wildcards, could lead to future suppressions which were not expected.

### Proposed Solution

Implement a "NaggingSynthesizer" stack synthesizer, this synthesizer would maintain state tracking what suppressions are found, and which suppressions are used. In the synthesize method, call super to synthesize the stack, and then perform checks to ensure all found suppressions were actually called by ignoreRule. If not, throw an error complaining of unused suppressions.

### Other information

This would not incur any breaking changes, and would be an optional implementation by requiring the implementor to use the NaggingSynthesizer stack synthesizer. 

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
This is somewhat tricky. If this were to be implemented we would have to consider the following 
1. Stack level suppressions would need to be accounted for
2. Applying suppressions with `applyToChildren` would cause errors when those suppressions get applied to non relevant children (could be worked around).

Additionally if implemented I think this should be an optional feature 

> Unused suppressions, especially for IAM policy wildcards, could lead to future suppressions which were not expected.

This could be a problem, but users do have the option to apply [granular suppressions](https://github.com/cdklabs/cdk-nag#suppressing-a-rule) (example 5) for better control over that situation.

**Comment by maclema** [comment]
I agree, this could potentially cause more pain than gain. I think [this pull request](https://github.com/cdklabs/cdk-nag/pull/799) will help avoid the type of unused suppressions I was considering (path misses)
