### ISSUE TITLE
bug: CdkNagValidationFailure when adding interface endpoints 

### ISSUE THREAD

**Issue by DennisLigtenberg** [cdklabs/cdk-nag#817]
### What is the problem?

I get a `CdkNagValidationFailure` for all interfaceEndpoints added to a VPC:

### Reproduction Steps

Using CDK Nag and adding an interface endpoint to a VPC eg:

`
vpc.addInterfaceEndpoint('KMS', {
      service: ec2.InterfaceVpcEndpointAwsService.KMS,
});
`

### What did you expect to happen?

Not getting a CdkNagValidationFailure but at worst a AwsSolutions-EC23 warning (cdk creates wildcard security groups for interfaceEndpoints)

### What actually happened?

When adding CDK Nag to a stack with interface endpoints following entry is contained in the warnings:
`
 CdkNagValidationFailure: 'AwsSolutions-EC23' threw an error during validation. This is generally caused by a parameter referencing an intrinsic function. For more details enable verbose logging.' The parameter resolved to to a non-primitive value "{"Fn::GetAtt":["VPCB9E5F0B4","CidrBlock"]}", therefore the rule could not be validated.
`

### cdk-nag version

1.12.38

### Language

Typescript

### Other information

The stack uses cdk 1.153.1

**Comment by dontirun** [comment]
This is the intended behavior for rules that must know a value but receive an intrinsic function instead.

In this case EC23 can't determine whether the ports violate the rule so this the validation error is thrown instead

**Comment by DennisLigtenberg** [comment]
Alright, thanks for the info! Is there a way to ignore suppress the specific validation warning? Suppressing the `AwsSolutions-EC23` warning doesn't seem to do the job.

**Comment by dontirun** [comment]
The `CdkNagValidationFailure` can be suppressed

**Comment by hoegertn** [comment]
@dontirun I totally get why the system cannot resolve intrinsic functions but on the other hand the concrete rule could understand `GetAtt CidrBlock` and know that the CIDR range of a VPC is not `/0`

What do you think?

**Comment by dontirun** [comment]
I think that's reasonable, though we would also need to verify that Resource that the referenced resource actually is a VPC

**Comment by surecloud-meason** [comment]
> The `CdkNagValidationFailure` can be suppressed

@dontirun 

How do you suppress the specific CdkNagValidationFailure. I'm getting the same issue but unable to suppress it via id.

**Comment by surecloud-meason** [comment]
@dontirun thanks couldnt find any documentation for that so appreciate it.

**Comment by dontirun** [comment]
@securw

Always happy take suggestions/PRs for improvements. What type of documentation would have helped in this case?

**Comment by surecloud-meason** [comment]
@dontirun Just clearer instructions on what is available to be used as an ID, my understanding is it was only the id of the rule.
