### ISSUE TITLE
SF1 triggers even when logging configuration is set to ALL

### ISSUE THREAD

**Issue by hearde** [cdklabs/cdk-nag#826]
### What is the problem?

State machine logging configuration might be set using overrides. In this case the nag still occurs even though the logging configuration is as specified.

### Reproduction Steps

```ts
import * as nag from 'cdk-nag';
import * as cdk from 'aws-cdk-lib';

const app = new cdk.App();
cdk.Aspects.of(app).add(new nag.AwsSolutionsChecks());
const stack = new cdk.Stack(app, 'sf1-repro');

const pass = new cdk.aws_stepfunctions.Pass(stack, 'Pass');
const stateMachine = new cdk.aws_stepfunctions.StateMachine(stack, 'StateMachine', {
  definition: pass,
  tracingEnabled: true
});
// nag.NagSuppressions.addResourceSuppressions(stateMachine, [
//   {id: 'AwsSolutions-SF1', reason: 'False alarm'}
// ]);
const policy = stateMachine.node.findChild('Role').node.findChild('DefaultPolicy') as cdk.aws_iam.Policy;
nag.NagSuppressions.addResourceSuppressions(policy, [
  {id: 'AwsSolutions-IAM5', reason: 'Needed for xray'}
]);

const logGroupName = 'MyLogGroup';
const logGroupArn = `arn:${stack.partition}:logs:${stack.region}:${stack.account}:log-group:${logGroupName}:*`

const stateMachineConstruct = stateMachine.node.defaultChild as cdk.aws_stepfunctions.CfnStateMachine;
stateMachineConstruct.addOverride(
  'Properties.LoggingConfiguration', {
    'Destinations': [{'CloudWatchLogsLogGroup': {'LogGroupArn': logGroupArn}}],
    'IncludeExecutionData': true,
    'Level': 'ALL'
});

```

### What did you expect to happen?

Successful `cdk synth`

### What actually happened?

```
[Error at /sf1-repro/StateMachine/Resource] AwsSolutions-SF1: The Step Function does not log "ALL" events to CloudWatch Logs.


Found errors
```

### cdk-nag version

2.12.43

### Language

Typescript

**Comment by dontirun** [comment]
Unfortunately `cdk-nag` won't be able to see the fix since property overrides take place after the CloudFormation template is synthesized. This is because `cdk-nag` performs validation prior to the synthesizing of the template.

https://github.com/cdklabs/cdk-nag#rules-and-property-overrides

**Comment by hearde** [comment]
@dontirun Thanks for pointing out that answer I missed in the readme.

However, I'd like to point out that [it is possible to run cdk-nag on a template](https://github.com/cdklabs/cdk-nag#using-on-cloudformation-templates), so what you are pointing out is not a hard limitation but rather a behavior choice. I think it is worth seriously considering the impact of false positives in a tool like this. If any appreciable portion of nags are things that developers should immediately suppress, the usefulness of the other nags rapidly goes to zero.
