### ISSUE TITLE
doc: reasoning behind `rules_to_suppress` metadata?

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [cdklabs/cdk-nag#837]
### Describe your issue?

I'd like to understand the reasoning behind adding all nag suppressions to the synth'd template. I don't see this documented anywhere. I may add a feature request to make this behavior configurable.

**Comment by dontirun** [comment]
`cdk-nag` was designed as a tool to make it easier for development and security teams to identify potential problems in CDK applications.

Many of the features are built around transparency (`NagReports`, forced reasons, granular suppressions, writing to the template).

The CloudFormation template is the source of truth for a CDK application, having the suppressions on the template make it a lot easier for those who view the template to understand the risks and decisions that have been made with the infrastructure.

**Comment by vito-laurenza-zocdoc** [comment]
That's fair enough in a general sense. I can only add our perspective that we consider our CDK code the source of truth and having the suppressions in the rendered template provides us with little to no value. I will open a feature request to make this behavior configurable. Thanks for the clarification!
