### ISSUE TITLE
Ensure EMR master has no public IP

### ISSUE THREAD

**Issue by jen-rich** [cdklabs/cdk-nag#91]
*Control ID:*
AC-4/AC-21(b)/SC-7/SC-7(3)

*AWS Config Rule:* 
emr-master-no-public-ip

*Story:*
As an AWS consultant
I would like to check if my EMR resource configuration is compliant (master has no public IP)
So that I can check if my application conforms with Control IDs AC-4, AC-21(b), SC-7, and SC-7(3) within NIST 800-53.

*Acceptance Criteria:*

    * Given a CDK stack with a *non-compliant EMR* resource
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack does not deploy and the consultant receives an explanation about the non compliant EMR instance for Control IDs AC-4, AC-21(b), SC-7, and SC-7(3) within NIST 800-53 .
    * Given a CDK stack with a *compliant EMR* resource and other compliant resources
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53.
    * Given a CDK stack *without an EMR* resource and other compliant resources:
        * When NIST-503 Secure Aspects is run
        * Then the CDK stack deploys and the consultant does not receive an explanation about NIST 800-53

**Comment by dontirun** [comment]
Added to `NIST 800-53` 'Excluded Rules' in the RULES file
