### ISSUE TITLE
bug: AwsSolutions-RDS10 and AwsSolutions-RDS15 are duplicates

### ISSUE THREAD

**Issue by valmaev** [cdklabs/cdk-nag#923]
### What is the problem?

Looks like AwsSolutions-RDS10 and AwsSolutions-RDS15 are duplicates. They're using the same rule behind the scenes:

* [RDS10](https://github.com/cdklabs/cdk-nag/blob/0da7426acfdab38a35142e3ce9322cc04d39dbd1/src/packs/aws-solutions.ts#L505)
* [RDS15](https://github.com/cdklabs/cdk-nag/blob/0da7426acfdab38a35142e3ce9322cc04d39dbd1/src/packs/aws-solutions.ts#L540)

### Reproduction Steps

1. Create Aurora Cluster with disabled termination protection in your stack.
2. Add `AwsSolutionsChecks` aspect to your stack.
3. Synthesize the stack.

### What did you expect to happen?

One error about disabled termination protection for the Aurora Cluster.

### What actually happened?

Two errors about disabled termination protection for the Aurora Cluster.

### cdk-nag version

2.14.45

### Language

Typescript

**Comment by dontirun** [comment]
Thanks for reporting 🤦! 

It looks like we can just get rid of `AwsSolutions-RDS15` without causing any problems
