### ISSUE TITLE
bug:  possible issue with AwsSolutions-COG1 

### ISSUE THREAD

**Issue by babeal** [cdklabs/cdk-nag#939]
### What is the problem?

Rule - AwsSolutions-COG1 - Cognito.CognitoUserPoolStrongPasswordPolicy validation is incorrect.  The check looks for requireDigits when the object property defined by CDK is requireNumbers.  

### Reproduction Steps

       ```
       const userPool = new cdk.aws_cognito.UserPool(this, "UserPool", {
            selfSignUpEnabled: true,
            autoVerify: { email: true },
            userVerification: {
                emailSubject: "Verify your email the app!",
                emailBody:
                    "Hello {username}, Thanks for signing up to the app! Your verification code is {####}",
                emailStyle: cdk.aws_cognito.VerificationEmailStyle.CODE,
                smsMessage:
                    "Hello {username}, Thanks for signing up to app! Your verification code is {####}",
            },
            passwordPolicy: {
                minLength: 8,
                requireDigits: true,
                requireUppercase: true,
                requireSymbols: true,
                requireLowercase: true,
            },
            removalPolicy: cdk.RemovalPolicy.DESTROY,
        });
        ```

### What did you expect to happen?

Should not get an error for violating strong password policy rule

### What actually happened?

Get an error for violating strong password policy rule

### cdk-nag version

2.15.9

### Language

Typescript

**Comment by dontirun** [comment]
I'm unable to replicate the error using the above snippet. I see a `AwsSolutions-COG2` warning and `AwsSolutions-COG3` error, but not a `AwsSolutions-COG1` error.

> The check looks for requireDigits when the object property defined by CDK is requireNumbers.

The cdk calls it [requireDigits](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cognito.PasswordPolicy.html#requiredigits) in the L2 construct which maps to requireNumbers on the L1.  I think cdk-nag properly [checks for the correct property](https://github.com/cdklabs/cdk-nag/blob/main/src/rules/cognito/CognitoUserPoolStrongPasswordPolicy.ts#L42)

**Comment by babeal** [comment]
@dontirun yea that makes sense.  I didn't realize the property name was remapped between the construct and L2.  Though I am still getting an error with that code.  I will set some break points in the package see what's being passed into the rule.

[Error at /master/Cognito/UserPool/Resource] AwsSolutions-COG1: The Cognito user pool does not have a password policy that minimally specify a password length of at least 8 characters, as well as requiring uppercase, numeric, and special characters.
