### ISSUE TITLE
feat: export test utils

### ISSUE THREAD

**Issue by webratz** [cdklabs/cdk-nag#944]
### Description

I'm using test [test utils](https://github.com/cdklabs/cdk-nag/blob/0da7426acfdab38a35142e3ce9322cc04d39dbd1/test/rules/utils.ts) to write tests for rules that I write for my organization.
Currently I have to copy and modify the code a bit so i can use it in my tests. It would be great if the test utils would also be exported, so they can be directly used.

### Use Case

Write tests for rules in own projects.

### Proposed Solution

Export the test utils

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dontirun** [comment]
Closing since this is something that we're not going to do
