### ISSUE TITLE
Question: Best way to suppress fine grained resources

### ISSUE THREAD

**Issue by bestickley** [cdklabs/cdk-nag#957]
### General Issue

Best way to suppress fine grained resources

### The Question

I have to use the below code to allow the error:
`[Error at /cosmos-back-end/RegisterApi/RegisterUser/ServiceRole/DefaultPolicy/Resource] AwsSolutions-IAM5[Resource::<IACertBucketE6AB2C0F.Arn>/*]: The IAM entity contains wildcard permissions and does not have a cdk-nag rule suppression with evidence for those permission.`

Code:
```ts
const userFn = new ApiDbFunction(this, "RegisterUser", {
      entry: fileURLToPath(
        new URL("user-fn/adapter/handler.ts", import.meta.url)
      ),
      environment: {
        AD_CLIENT_ID: adClientId,
        AD_CLIENT_SECRET: adClientSecret,
        AD_TENANT_ID: adTenantId,
        STAGE: stage,
        BUCKET_NAME: iaCertBucket.bucketName,
      },
      cluster,
    });
    iaCertBucket.grantPut(userFn);
    const bucketLogicalId = Stack.of(this).getLogicalId(
      iaCertBucket.node.defaultChild as CfnBucket
    );
    NagSuppressions.addResourceSuppressions(
      userFn,
      [
        {
          id: "AwsSolutions-IAM5",
          reason: "AwsSolutions-IAM5",
          appliesTo: [
            "Action::s3:Abort*",
            `Resource::<${bucketLogicalId}.Arn>/*`,
          ],
        },
      ],
      true
    );
```

Getting the logical id is a little cumbersome. Is there a better way or is this how I must use a fine-grained suppression for a resource?

### cdk-nag version

2.14.41

### Language

Typescript

**Comment by dontirun** [comment]
You can use the `<IACertBucketE6AB2C0F.Arn>/*` that is listed in the error. That value is going to remain consistent within the application.

**Comment by bestickley** [comment]
@dontirun, is that true even if I move the bucket to a different stack?

**Comment by dontirun** [comment]
I don't know the answer to that, but I would imagine that you be able to update the reference when doing that sort of refactoring.

To be clear, there isn't anything wrong with what you're doing if that's what you would like to do.

**Comment by bestickley** [comment]
Got it. Thank you!
