### ISSUE TITLE
bug: Cannot ignore `AwsCustomResource` for `NIST.800.53.R4-LambdaInsideVPC`

### ISSUE THREAD

**Issue by kylelaker** [cdklabs/cdk-nag#959]
### What is the problem?

The `AwsCustomResource` construct does not support a `vpc` prop; however, it is very common within the CDK codebase itself as well as within other libraries. It would be extremely useful to be able to ignore the `NIST.800.53.R4-LambdaInsideVPC` (and similar rules) for this construct. It seems that there is some sort of an issue with 

### Reproduction Steps

```ts
import 'source-map-support/register';
import * as cdk from "aws-cdk-lib";
import * as cr from "aws-cdk-lib/custom-resources";

import { NagSuppressions, NIST80053R4Checks } from "cdk-nag";

const app = new cdk.App();
const stack = new cdk.Stack(app, "SampleStack");
cdk.Aspects.of(stack).add(new NIST80053R4Checks());
const problemResource = new cr.AwsCustomResource(stack, "ProblemResource", {
  onCreate: {
    service: 's3',
    action: 'listObjectsV2',
    parameters: {
      Bucket: 'my-bucket',
    },
    physicalResourceId: cr.PhysicalResourceId.of('id'),
    outputPaths: ['Contents.0.Key', 'Contents.1.Key'], // Output only the two first keys
  },
  policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
    resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
  }),
});

NagSuppressions.addResourceSuppressions(problemResource, [
  {
    id: "NIST.800.53.R4-LambdaInsideVPC",
    reason: "Because I want to",
  },
  {
    id: "NIST.800.53.R4-IAMNoInlinePolicy",
    reason: "This ignore _does_ work",
  },
], true);
```

### What did you expect to happen?

`NIST.800.53.R4-LambdaInsideVPC` was ignored for `ProblemResource` and synthesis was successful.

### What actually happened?

Synthesis failed because of

```
[Error at /SampleStack/AWS679f53fac002430cb0da5b7982bd2287/Resource] NIST.800.53.R4-LambdaInsideVPC: The Lambda function is not VPC enabled - (Control IDs: AC-4, SC-7, SC-7(3)).
```

### cdk-nag version

2.15.26

### Language

Typescript

### Other information

Maybe it'd be possible to use the `appliesTo` option here? But the filter that would be used for that is unclear. This is a check that it's desirable to not apply too broadly.

It seems viable to also use `addResourceSuppressionsByPath` but having to encode the path to the resource is also suboptimal, and I'd like to be able to ignore any custom resources. It seems like `AWS679f53fac002430cb0da5b7982bd2287` is a pretty stable name but I don't see it documented anywhere; it just seems to [consistently be used](https://cs.github.com/aws/aws-cdk?q=AWS679f53fac002430cb0da5b7982bd2287%20language%3ATypeScript).

**Comment by dontirun** [comment]
The `appliesTo` option isn't related to this issue.

In this case you are most likely going to need to use `addResourceSuppressionsByPath`. That functionality was added for this use case. The CDK nests the Lambda used for the `AwsCustomResource` under the main Stack, I believe that's because that Lambda is shared across all  `AwsCustomResources` (You can confirm the sharing behavior by creating a new `AwsCustomResource` with different calls and looking at the lambda code).

Related issue for context https://github.com/cdklabs/cdk-nag/issues/414

**Comment by kylelaker** [comment]
Okay, yeah, I've now gotten this working with `addResourceSuppressionsByPath`. It looks like the name/`node.path` are pretty consistent so that seems like a pretty good solution. Thanks for the context/information!

And at least for the very specific rule, I opened https://github.com/aws/aws-cdk/pull/21357 which may help with an actual remediation.
